#!/usr/bin/env bash

# restart awesomewm and log/notify new profile
echo "awesome.restart()" | awesome-client
(sleep 2 && notify-send "Display profile $AUTORANDR_CURRENT_PROFILE") &
logger "Display profile $AUTORANDR_CURRENT_PROFILE"

