#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# backlight
"$HOME/git/linux-scripts/backlight"

# monitor
"$HOME/git/linux-scripts/monitor" enable

# NM UI
nm-applet &

# TP battery tresholds
# "$HOME/git/linux-scripts/set-tpacpi"

# dropbox
dropbox &

# set dbus address for cron stuff
"$HOME/git/linux-scripts/set-dbus-address"

# composite manager
"$HOME/git/linux-scripts/compton-toggle"

# start thunar in daemon mode
thunar --daemon &

# adjust keyboard repeat rate
xset r rate 250 35

# conky
(sleep 10 && conky -c "$HOME/git/dotfiles/arch/conkyrc" -d) &

# start thunderbird and gpodder
(sleep 10 && thunderbird) &
(sleep 60 && gpodder) &

# store boot log
(sleep 60 && journalctl -p 5 -b -o short-precise --no-pager > /tmp/boot-log) &

session=${1:-awesome}
case $session in
    awesome           ) exec awesome >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr;;
    bspwm             ) exec bspwm;;
    catwm             ) exec catwm;;
    cinnamon          ) exec cinnamon-session;;
    dwm               ) exec dwm;;
    enlightenment     ) exec enlightenment_start;;
    ede               ) exec startede;;
    fluxbox           ) exec startfluxbox;;
    gnome             ) exec gnome-session;;
    gnome-classic     ) exec gnome-session --session=gnome-classic;;
    i3|i3wm           ) exec i3;;
    icewm             ) exec icewm-session;;
    jwm               ) exec jwm;;
    kde               ) exec startkde;;
    lxde              ) exec startlxde;;
    mate              ) exec mate-session;;
    monster|monsterwm ) exec monsterwm;;
    notion            ) exec notion;;
    openbox           ) exec openbox-session;;
    unity             ) exec unity;;
    xfce|xfce4        ) exec startxfce4;;
    xmonad            ) exec xmonad;;
    # no known session, try to run it as command
    *) exec "$1";;
esac

