#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# TODO: Check if stuff is already running!

sudo dhcpcd -b -q enp0s25

# backlight
$HOME/git/linux-scripts/backlight

# monitor
$HOME/git/linux-scripts/monitor enable

# NM UI
nm-applet &

# TP battery tresholds
$HOME/git/linux-scripts/set-tpacpi

# dropbox
dropbox &

# set dbus address for cron stuff
$HOME/git/linux-scripts/set-dbus-address

# composite manager
compton --backend glx --paint-on-overlay --vsync opengl-swc -fb -D3

# start thunar in daemon mode
thunar --daemon &

# start udiskie for automounting usb's
udiskie -2 -s &

# adjust keyboard repeat rate
xset r rate 250 35

# conky
(sleep 10 && conky -c $HOME/git/dotfiles/arch/conkyrc -d) &

# start thunderbird
(sleep 10 && thunderbird) &

# store boot log
(sleep 60 && journalctl -p 5 -b -o short-precise --no-pager > /tmp/boot-log) &

#(sleep 60 && $HOME/git/linux-scripts/samba-connect) &     <-- looks like they're being connected elsewhere!

(sleep 60 && gpodder) &

#(sleep 60 && qbittorrent) &

#env LD_PRELOAD=/home/fabian/git/fullscreenhack/libfshack-npapi.so

session=${1:-awesome}
case $session in
    awesome           ) exec awesome >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr;;
    bspwm             ) exec bspwm;;
    catwm             ) exec catwm;;
    cinnamon          ) exec cinnamon-session;;
    dwm               ) exec dwm;;
    enlightenment     ) exec enlightenment_start;;
    ede               ) exec startede;;
    fluxbox           ) exec startfluxbox;;
    gnome             ) exec gnome-session;;
    gnome-classic     ) exec gnome-session --session=gnome-classic;;
    i3|i3wm           ) exec i3;;
    icewm             ) exec icewm-session;;
    jwm               ) exec jwm;;
    kde               ) exec startkde;;
    lxde              ) exec startlxde;;
    mate              ) exec mate-session;;
    monster|monsterwm ) exec monsterwm;;
    notion            ) exec notion;;
    openbox           ) exec openbox-session;;
    unity             ) exec unity;;
    xfce|xfce4        ) exec startxfce4;;
    xmonad            ) exec xmonad;;
    # no known session, try to run it as command
    *) exec $1;;
esac

