#!/usr/bin/env bash

# backlight - turn down first to ensure it's set according to charging status
"$HOME/git/linux-scripts/backlight" on

# monitor
"$HOME/git/linux-scripts/monitor" enable

# set dbus address for cron stuff
# "$HOME/git/linux-scripts/set-dbus-address"

# adjust keyboard repeat rate
xset r rate 250 35

# background apps
udiskie & # NOTE: also has a --tray
thunar --daemon &
picom &
nm-applet &
ulauncher --no-window-shadow &
xfce4-clipman &
synology-drive &
# dropbox &
pasystray &
caffeine &
blueman-applet &
# NOTE: seems to suspend 5 mins later for some reason...
xautolock -time 5 -locker "$HOME/git/linux-scripts/fancy-lock" \
  -corners 00+- -cornerdelay 3 -cornerredelay 30 \
  -detectsleep -killtime 10 -killer 'sudo systemctl suspend' &
conky -c "$HOME/git/dotfiles/arch/conkyrc" -d

signal-desktop &
ferdi &
# slack &
spotify &

# store boot log
(sleep 60 && journalctl -p 5 -b -o short-precise --no-pager > /tmp/boot-log) &

session=${1:-awesome}
case $session in
    awesome           ) exec awesome >> /var/log/awesome/stdout 2>> /var/log/awesome/stderr;;
    bspwm             ) exec bspwm;;
    catwm             ) exec catwm;;
    cinnamon          ) exec cinnamon-session;;
    dwm               ) exec dwm;;
    enlightenment     ) exec enlightenment_start;;
    ede               ) exec startede;;
    fluxbox           ) exec startfluxbox;;
    gnome             ) exec gnome-session;;
    gnome-classic     ) exec gnome-session --session=gnome-classic;;
    i3|i3wm           ) exec i3;;
    icewm             ) exec icewm-session;;
    jwm               ) exec jwm;;
    kde               ) exec startkde;;
    lxde              ) exec startlxde;;
    mate              ) exec mate-session;;
    monster|monsterwm ) exec monsterwm;;
    notion            ) exec notion;;
    openbox           ) exec openbox-session;;
    unity             ) exec unity;;
    xfce|xfce4        ) exec startxfce4;;
    xmonad            ) exec xmonad;;
    # no known session, try to run it as command
    *) exec "$1";;
esac

